- pom.xml
- src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReport.java
- src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationReport.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReportTest.java
* Use `java.time.Instant` to capture elapsed time of FS migration
* Stop "timing" the migration when it reaches terminal state (`DONE` or `FAILED`)
* Time migration based on when migration enters `RUNNING` state from non-`RUNNING` state
* Test with mocked clock
> CHET-119: Time FS migration

- src/main/java/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationProgressEndpoint.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/DirectoryStreamCrawler.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/S3Uploader.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationErrorReport.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReport.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFilesystemMigrationProgress.java
- src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FailedFileMigration.java
- src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationErrorReport.java
- src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationProgress.java
- src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationReport.java
- src/test/java/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationProgressEndpointTest.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationErrorReportTest.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReportTest.java
* Able to get full status of FS migration
* status
* completed files
* failed files
* Fixes bug where migration is not set to running after starting
If there is a large number of errors then the response can get very large. I had a migration fail completely (local jira with amps:run) and the API response was 1.2MB. We may want to have a separate endpoint for the errors and implement pagination. Thoughts?
> CHET-120: FS migration progress rest endpoint

- src/main/java/com/atlassian/migration/datacenter/core/fs/DirectoryStreamCrawler.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/S3Uploader.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReport.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFilesystemMigrationProgress.java
- src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationProgress.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/DirectoryStreamCrawlerTest.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderTest.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationProgressTest.java
I've implemented another metric in the FS migration progress which will make it much easier to see how the migration is going: In flight files
This should be the number of files which are being uploaded and have not been confirmed to be uploaded successfully. This is a good indicator on the progress the app is making through the migration.
> FS progress report in flight files

- src/main/java/com/atlassian/migration/datacenter/core/fs/S3Uploader.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationErrorReport.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReport.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFilesystemMigrationProgress.java
- src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FailedFileMigration.java
- src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationErrorReport.java
- src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationProgress.java
- src/test/java/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationProgressEndpointTest.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderIT.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderTest.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationErrorReportTest.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationProgressTest.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReportTest.java
We were getting `ConcurrentModificationException` because the `migratedFiles` data structure wasn't thread-safe. I fixed that and then the data strucute was too big to be serialised sensibly. I've just refactored the migrated files property to be a count of migrated files.
> Fix fs migration reporting

- src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/spi/MigrationServiceV2.java
- src/main/java/com/atlassian/migration/datacenter/spi/MigrationStage.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java
Paired with @theghostwhoforks 
This is the new state management service based on the specification from #30 
There is just one distinction and that is that there is no ability to set the stage directly.
Services either tell the state machine to move to the next stage (once they are done). The next stage is determined by the current stage. Services can also tell the state machine to move to an Error state.
The only pitfall with this approach is recovering from the Error state as it can potentially have multiple next states that aren't known until runtime, depending on the recovery approach. I suspect we may need to revert to setting the stage directly.
Should we defer that decision to when we start handling the unhappy path?
> CHET-124: implement state management service

- src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/spi/MigrationServiceV2.java
- src/main/java/com/atlassian/migration/datacenter/spi/MigrationStage.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java
After working on the quickstart deployment stage I found an issue where you want to call "next stage" multiple times within the one service as you have the transition from:
Deploy application -> wait deploy application -> deploy migration stack
I don't think you want to call `nextStage()` to do that as `nextStage()` tries to encapsulate the path through stages however this stage expects a specific sequence when doing that.
I tried to move the waiting to `deploy application` to a separate service but this was also fruitless as you need to know when to start waiting for the deployment to finish which is impossible without some sort of `onTransition` hook. At this point, we'd basically be back with the heavyweight state pattern which we decided was undesirable.
After discussion with Varun, …
> Drop next stage encoding

- src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- src/main/java/com/atlassian/migration/datacenter/dto/MigrationContext.java
- src/main/java/com/atlassian/migration/datacenter/spi/MigrationServiceV2.java
- src/main/java/com/atlassian/migration/datacenter/spi/infrastructure/ApplicationDeploymentService.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceTest.java
Bring quickstart deployment into state machine. Manages states:
DEPLOY_APPLICATION -> WAIT_DEPLOY_APPLICATION -> DEPLOY_MIGRATION_STACK
Also introduces `MigrationContext` where we can persist all data related to the migration that other stages may need access to. The `MigrationContext` is linked to the `Migration`.
The new service needs to be connected to a REST API but I figured we do that once we actually start tackling the UI.
> CHET-128: quickstart state machine

- src/main/resources/atlassian-plugin.xml
Otherwise, you get table not found errors.
These screenshots verify the relationship is working properly
And showing the MigrationContext references the migration ID
> Add MigrationContext entity to atlassian-plugin.xml ao declaration

- src/main/java/com/atlassian/migration/datacenter/core/fs/S3Uploader.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReport.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFilesystemMigrationProgress.java
- src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationProgress.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderTest.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationProgressTest.java
Adam was observing that the in-flight files were being reported as a negative number. I wasn't able to reproduce this locally. I had a look through the code and the in-flight file reporting is not very consistent anyway: Files which have an error do not decrement the files in-flight counter and it would take a non-trivial amount of effort to correct this.
The aim of the files-in-flight counter was to get an indication of how far behind the crawler the uploader is. With that in mind, I've refactored the files-in-flight to be a "files with commenced upload" counter. This still lets us track the uploader without reporting incorrect information. I'm open to the possibility that we could just drop this notion altogether.
> CHET-148: Re-work in-flight file reporting

- pom.xml
- src/main/java/com/atlassian/migration/datacenter/core/aws/SSMApi.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/SSMApiIT.java
* Manages SSM client
* Exposes key SSM operations
* Reduced complexity of return types where possible
* Builds in sensible defaults.
> CHET-154: Build thin wrapper over SSM API

- pom.xml
- src/main/java/com/atlassian/migration/datacenter/core/application/DatabaseConfiguration.java
- src/main/java/com/atlassian/migration/datacenter/core/application/JiraConfiguration.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/db/MigrationStatus.java
- src/main/java/com/atlassian/migration/datacenter/core/db/DatabaseExtractor.java
- src/main/java/com/atlassian/migration/datacenter/core/db/DatabaseExtractorFactory.java
- src/main/java/com/atlassian/migration/datacenter/core/db/PostgresExtractor.java
- src/test/java/com/atlassian/migration/datacenter/core/application/JiraConfigurationTest.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationServiceIT.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/db/PostgresMigrationIT.java
- src/test/java/com/atlassian/migration/datacenter/core/db/PostgresExtractorIT.java
- src/test/java/com/atlassian/migration/datacenter/util/AwsCredentialsProviderShim.java
This add the DatabaseMigrationService and testing. As discussed IRL, this is slightly messy as the S3Uploader, etc. has slightly FS-migration-specific; the next step is to refactor-out the common areas into common components, but this is better as a 2-step process.
> CHET-145: Add database migration service

- src/main/dc-migration-assistant-fe/components/aws/quickstart/__snapshots__/quickstartToAtlaskit.test.tsx.snap
- yarn.lock
This resolves the security vulnerability in `acorn@7.1.0`. I simply deleted the node_modules directory and the lockfile and regenerated it completely so we should have a more efficient resolution now
> Re-Resolve yarn dependencies

- src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationServiceIT.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationServiceIT.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationServiceTest.java
- src/test/java/com/atlassian/migration/datacenter/util/AwsCredentialsProviderShim.java
This is separate from the service refactoring; this one ensures that we have a working baseline for the S3FilesystemMigrationService tests.
> CHET-173: Refactor S3FilesystemMigrationService to be more testable, and expand integration tests

- src/main/java/com/atlassian/migration/datacenter/api/develop/DevelopEndpoint.java
- src/main/java/com/atlassian/migration/datacenter/spi/MigrationStage.java
- src/test/java/com/atlassian/migration/datacenter/api/develop/DevelopEndpointTest.java
The JSON payload is for example `"FS_MIGRATION_COPY"`.
Jackson is very picky with enums. Other option is to use `@PathParam` but I will push this forward and it is also availble from Postman.
> CHET-142: Dev endpoint to set stage

- src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantProfileSpecificConfiguration.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/spi/MigrationStage.java
- src/test/java/com/atlassian/migration/datacenter/spi/MigrationStageTest.java
A small PR that will make the profiled bean a primary. This is useful so that we do not need to create negated profile scoped beans like we have currently.
When the profile to allowTransitions is active, 2 migrations beans are registered, but the bean annotated with primary is the only one that is injected. 
Additionally, this cleans up migration state and removes the static method to check if transitions are valid
> CHET-169: Clean up migration service wireup & migration stage 

- src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArtifactS3UploadService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/ssm/SuccessfulSSMCommandConsumer.java
- src/main/java/com/atlassian/migration/datacenter/core/exceptions/FileSystemMigrationFailure.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/FilesystemUploader.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/S3Uploader.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/Uploader.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/download/s3sync/S3SyncFileSystemDownloadManager.java
- src/main/java/com/atlassian/migration/datacenter/core/fs/download/s3sync/S3SyncFileSystemDownloader.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderIT.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderTest.java
- src/test/java/com/atlassian/migration/datacenter/core/fs/download/s3sync/S3SyncFileSystemDownloaderTest.java
- templates/migration-stack/migration-helper.yml
- templates/migration-stack/pkg/parse_sync_output.py
This addresses some PR feedback and does a minor refactor so that the s3 file system migration service does fewer things.
* Use exception from file system upload and download as the source of truth for migration failure.
* Add more details to exceptions thrown during file system migration
> CHET-187: fs migration ssm download cleanup

- src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
Spring beans with mutable data are effectively global variables. We should synchronise any mutation points.
> Add synchronisation points to state machine.

- src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/MigrationStageCallback.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArchivalService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArchiveStageTransitionCallback.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArtifactS3UploadService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseUploadStageTransitionCallback.java
- src/main/java/com/atlassian/migration/datacenter/spi/MigrationService.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArchivalServiceTest.java
The `transitionToNext` of database archive was the same as `transitionToStart` of the database restore which would have caused an exception. I've refactored the callbacks so that they simply assert they are in the expected stage before starting instead of transitioning to the start stage. The transition to the start stage of any operation will be done by the `transitionToNext` of the previous operation.
> Fix duplicate transition between db export and import

- src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/db/restore/TargetDbCredentialsStorageService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- src/main/java/com/atlassian/migration/datacenter/dto/MigrationContext.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceTest.java
- Stores database password encrypted in the migration context.
- Hardcodes the database user
- Refactor access to the migration context so it goes through the MigrationService
- Make the relationship between migration context and migration bidirectional
> CHET-202: Securely store new db credentials

- src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/db/restore/TargetDbCredentialsStorageService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- src/main/java/com/atlassian/migration/datacenter/dto/Migration.java
- src/main/java/com/atlassian/migration/datacenter/spi/MigrationService.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceTest.java
* Creaet bidirectional link between Migration and Migration Context
* Create method in migration service for accessing migration context
* Refactor dependents on migration context to use the new method
> Expose migration context via migration service

- pom.xml
- src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/db/restore/TargetDbCredentialsStorageService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- src/main/java/com/atlassian/migration/datacenter/dto/MigrationContext.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceTest.java
* Store database password in AWS secrets manager instead of migration context
Originally we were going to use the migration context to provide the DB password as a parameter to the migration stack CloudFormation template. However, this is not recommended by AWS ([source](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#creds)). Instead we store the credentials as a string with Secrets Manager under the name:
`com.atlassian.migration.db.target.[migration_deployment_id].applicationPassword`
where `migration_deployment_id` is the ApplicationDeploymentId of the current migration context
> CHET-190: pass target DB credentials to secretsmanager

- templates/migration-stack/migration-helper.yml
- templates/migration-stack/pkg/migration-helper.yml.src
This extends the existing custom resource used to open the EFS security group up to the migration stack to also update the RDS security group.
Screenshots for proof:
**The helper stack security group**
**The RDS security group provided as a parameter**
**The RDS security group opened up for postgresql after deployment**
**The RDS security group closed after destroying the migration stack**
> CHET-195: Open RDS Security group to migration helper

- src/main/java/com/atlassian/migration/datacenter/api/db/DatabaseMigrationEndpoint.java
DB migration endpoint had same REST path as the fs migration endpoint. This was causing the REST API filter instantiation to fail.
> FIX: de-dupe rest endpoints

- src/main/java/com/atlassian/migration/datacenter/api/aws/CloudFormationEndpoint.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/CloudformationDeploymentService.java
- src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- src/main/java/com/atlassian/migration/datacenter/dto/MigrationContext.java
- src/main/java/com/atlassian/migration/datacenter/spi/infrastructure/InfrastructureDeploymentStatus.java
- src/main/java/com/atlassian/migration/datacenter/spi/infrastructure/MigrationInfrastructureDeploymentService.java
- src/test/java/com/atlassian/migration/datacenter/api/aws/CloudFormationEndpointTest.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentServiceTest.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/CloudformationDeploymentServiceTest.java
- src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceTest.java
* Takes logic from quick start deployment and hoists it into a superclass
* Quickstart and migration template deployment inherit from this class
* Use template method to handle migration stage transitions
* Integrating migration stack deployment with state machine
> CHET-115: deploy migration stack service

- pom.xml
* Fix the `sourceDirs` for kotlin tests - this is then propagated to child modules
* Removed `.java` qualifier for tests
* Tested also `-Pintegration` profile - even though interestingly we don't have an integration test in `api` package (I had created dummy one for the test)
* Added kotlin incremental compilation - https://kotlinlang.org/docs/reference/using-maven.html#incremental-compilation
> CHET-223: Fix kotlin test maven configuration

- .github/workflows/mvn_test.yml
I've cleaned up the history of this branch, it was a lot of mess with Github Actions trial and error.
* We need to upload an artifact to share it across jobs
* It needs to be uploaded only from one step from the strategy matrix. I've picked unit tests on Java 11
* The variables are managed from Github secrets
* So far we are doing just a basic check whether the plugin was installed, more extensive tests are coming.
* Branch is now configurable via DOGFOODING_REF github secrets (`refs/heads/master` by default)
> CHET-183: Update dogfooding on each merge to master

- frontend/src/main/dc-migration-assistant-fe/components/aws/auth/AuthenticateAWS.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickStartStatus.tsx
- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
* Interface for marking up progress page with actual progress
* Periodically update the data (every minute)
* Handle loading state
* Dummy function in FS page
* "Next" button is disabled until progress is complete
* Actually implement it for the FS page
> CHET-232: progress data callbacks

- api/src/test/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationProgressEndpointTest.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3Uploader.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReport.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFilesystemMigrationProgress.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderIT.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationProgressTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReportTest.java
- spi/src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationProgress.java
The queue was not being emptied after "acknowledging" all the responses so we were repeating ourselves many times.
> CHET-242: Correct "migrated files" count being inflated

- api/src/test/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationProgressEndpointTest.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/download/s3sync/S3SyncFileSystemDownloadManager.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReport.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFilesystemMigrationProgress.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/download/s3sync/S3SyncFileSystemDownloadManagerTest.java
- spi/src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationProgress.java
Computes the number of files downloaded on the remote application using the S3 sync output and the known number of files on the system.
Could fail if Jira is restarted during the migration as the report is not persisted to DB
> CHET-243: remote download status

- api/src/test/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationProgressEndpointTest.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/ssm/SuccessfulSSMCommandConsumer.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/download/s3sync/S3SyncFileSystemDownloadManager.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReport.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReportTest.java
- spi/src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FilesystemMigrationStatus.java
* When uploading to S3 set status of FS migration to "UPLOADING"
* When downloading on remote host, set status to "DOWNLOADING".
* This allows us to expose more state in the UI.
> CHET-236: expose fs migration meta status

- api/src/test/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationProgressEndpointTest.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/DirectoryStreamCrawler.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationReport.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFilesystemMigrationProgress.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/DirectoryStreamCrawlerTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/reporting/DefaultFileSystemMigrationProgressTest.java
- spi/src/main/java/com/atlassian/migration/datacenter/spi/fs/reporting/FileSystemMigrationProgress.java
We expose when FS crawl is complete because at that point you can determine the exact progress of the migration by checking the `filesFound` of the fs migration status.
> CHET-244: expose when fs crawl is complete

- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
This is after getting feedack from Hanna. Having the file progress going from a large number to zero then counting up again is confusing. We will just use the progress bar.
> CHET-245: Remove FS progress strings; increase poll rate of FS progress

- frontend/src/main/dc-migration-assistant-fe/api/migration.ts
- frontend/src/main/dc-migration-assistant-fe/components/Home.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/auth/AuthenticateAWS.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/ErrorFlag.tsx
* Call API to create migration when "start" is clicked
* Render error flag when creation fails
Note: Does not redirect to next page as that is being left to CHET-278 so that it can be done in a consistent manner.
> CHET-284: start migration

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/db/DatabaseMigrationEndpoint.kt
- frontend/src/main/dc-migration-assistant-fe/api/db.ts
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/ProvisioningStatusPage.tsx
- frontend/src/main/dc-migration-assistant-fe/components/db/DatabaseMigration.tsx
- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.test.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
* Implement API call to start DB transfer
* Implement detecting if DB transfer is already in progress when loading page
* Refactor `MigrationTransferPage` to handle the "check if already started" logic
No appearance changes.
> CHET-280: Wire up start db transfer

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/CfnApi.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArtifactS3UploadService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationService.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArtifactS3UploadServiceTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationServiceTest.java
* Fix `S3AsyncClient` initialisation in `DatabaseArtifactS3UploadService` - the client was null because our `@PostConstruct` methods are not working so for now we need to init the client manually
* I've removed stored `CfnApi` client as it is storing a state that is possible to change and the client would be stale.
* Add tests to cover the case (+some more)
> CHET-263: Fix DB upload + some other bugs

- frontend/src/main/dc-migration-assistant-fe/api/migration.ts
- frontend/src/main/dc-migration-assistant-fe/components/Home.test.tsx
- frontend/src/main/dc-migration-assistant-fe/components/Home.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
* Implement check for if migration is started
* Render warning message if migration is already started
* Render button or redirect when migration is started and take user to their current step.
> CHET-285: hide "start migration" when migration is started

- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/ProvisioningStatusPage.tsx
- frontend/src/main/dc-migration-assistant-fe/components/db/DatabaseMigration.tsx
- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.test.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPageActions.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferProgress.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/migration-timing.ts
* Refactor MigrationTransferPage into smaller components, it was a bit of a behemoth
* Implement `nextRoute` as a prop of the MigrationTransfer shared component
* Wire up the next routes of all steps which require a "click" to proceed to the next step of each to go to their respective next step.
> CHET-289: Navigate between migration steps using "next" button

- frontend/src/main/dc-migration-assistant-fe/api/migration.ts
- frontend/src/main/dc-migration-assistant-fe/stage/Validation.tsx
- frontend/src/main/dc-migration-assistant-fe/utils/api.ts
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
Add a validation error flag component.
Refactor to use the migration api
2 stages of the component -
* When stage is validation
* When stage is not validation
> CHET-272: Add a error flag to highlight out of sequence migration step

- frontend/src/main/dc-migration-assistant-fe/components/Home.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/auth/AuthenticateAWS.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickStartDeploy.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/quickstartToAtlaskit.tsx
* Implements "Automatic" navigation transitions to the next step after submission of
* Migration creation
* Quickstart form submission
* Authentication
* Updates the s3 bucket to the production bucket with the latest version of the template parameters.
* Fixes a bug where the availability zones were being serialised as JSON instead of a comma-separated list
* Bit of a cleanup on the quickstart form
* Default to string input if the quickstart form parameter type isn't recognised
> CHET-278: automated next step transitions

- templates/migration-stack/migration-helper.yml
- templates/migration-stack/pkg/migration-helper.yml.src
* When doing `pg_dump` with directory format the `--no-owner` and `--no-acl` flags are ignored. These flags need to be instead used when running `pg_restore`, if the original table owner was different that the target stack (`atljira` in our case), the restore failed
* The script was always returning exit code 0 so it was always reported successful and DC migration plugin was always 😀  even when it should be a bit 😞 . It now exits with `1` if unsuccessful (for all sort of different reasons)
* The RDS I was restoring data to had the relationships in it - I am not sure how it happened - but to be sure I've included `--clear --if-exists`. We can investigate later - right now, the whole cycle to get the stack up and running makes this nightmare.
* I've uploaded the `migration-stack.yaml` to …
> CHET-286: update migration helper to drop owner and be more resilient

- func-tests/src/test/kotlin/com/atlassian/migration/api/MigrationEndpointRestTest.kt
This is a fix for now but it is not ideal.
Testing against dogfooding instance that is used will be quite tricky. I think it would be good to introduce a testing beacon that we can ping to verify state of the plugin and verify basic diagnostics.
I've created:
https://aws-partner.atlassian.net/browse/CHET-307
> fix the REST test running against dogfooding

- .env
- .env.development
- .gitignore
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- frontend/config/webpack.config.js
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickStartDeploy.tsx
OK, so this PR adds the ability to parameterise template URLs both in the FE and backend code flows
On the server side, if we want to specify a template URL for deploy, we should specify a system property like so - `-Dquickstart.template.url=https://dcd-slinghost-templates.s3-ap-southeast-2.amazonaws.com/trebuchet/tests/existing-vpc/quickstart-jira-dc.template.yaml ` to specify the DC template without VPC.
On the front end, things get a bit more interesting. Obviously, the FE app can't read environment variables at runtime. We can inject the template URLs at build time. To do this, we create a webpack plugin that reads from a `.env` file (located in the project root) and creates a dictionary with keys having a prefix (`process.env.`) and suffixed by the key value defined in the `.env` …
> Chet 311 parameterise cfn template url

- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/CancelButton.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPageActions.tsx
- frontend/src/main/dc-migration-assistant-fe/components/warning/WarningStage.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
* Internationalization for Warning page
* Extract common `CancelButton`
* The next page after FS migration is the Warning page now
* Add cancel button on the warning page
* Rename the submit button from `Continue` to `Next`
> CHET-320: Create common CancelButton component and update the design

- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
- frontend/src/main/dc-migration-assistant-fe/components/warning/WarningStage.tsx
* added Learn More link that links to KB article with description for the downtime.
** The anchor doesn't work properly but I am not sure if this is expected and @ddomingorh does have a version prepared or we need to fix the link. I've left a comment on https://aws-partner.atlassian.net/browse/CHET-329?focusedCommentId=10144
* I've restyled the page so it is more spacious. I think it would be good to have some unified and consistent styles across the page but I would leave that post-MVP
* Lint fix
> CHET-329: Add learn more link

- frontend/src/main/dc-migration-assistant-fe/components/MigrationStageRenderer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/ProvisioningStatusPage.tsx
- frontend/src/main/dc-migration-assistant-fe/components/db/DatabaseMigration.tsx
- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/Progress.ts
* Implement notion of _critical failure_ in `Progress` structure
* Handle setting of `failed` for each stage of migration
* Use common transfer page to redirect to error page in case of `failed`
> CHET-333: redirect to error path on failure

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentService.java
- templates/migration-stack/migration-helper.yml
- templates/migration-stack/pkg/migration-helper.yml.src
* Return either exit code from `pg_restore` if it wasn't `0` or print information with the errors from migration and return `0` as exit code. `pg_dump` returns non-zero code only with fatal errors - e.g. the directory is missing.
* Formatting of the error messages (when we expect people to read the log)
* Added ability to provide migrationStackId via system property
* Uploaded `migration-helper.yml` to `trebuchet-public-resources` S3 bucket and made it public
> CHET-322: Exit with 0 with non-critical errors from pg_restore

- jira-e2e-tests/helpers/README.md
- jira-e2e-tests/helpers/jira-psql-compose.yml
- jira-e2e-tests/helpers/upload-plugin
- jira-e2e-tests/support/index.js
This adds a docker-compose config and helper scripts to install the current plugin. See readme for details.
> Add some helper scripts for blitz testing.

- frontend/src/main/dc-migration-assistant-fe/api/provisioning.ts
When the application provisioning is complete but the migration infrastructure provisioning hasn't started, it will show "preparing migration infrastructure" as seen in below screenshot.
> CHET_295: Fix early "complete" between application and migration provisioning

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/MigrationEndpoint.kt
- api/src/test/kotlin/com/atlassian/migration/datacenter/api/MigrationEndpointTest.kt
- spi/src/main/java/com/atlassian/migration/datacenter/spi/MigrationService.java
Remove all migrations w/o considering the current stage of the migration
> CHET-209: Make reset API delete migrations irrespective of stage

- frontend/src/main/dc-migration-assistant-fe/api/fs.ts
- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/Progress.ts
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
* Refactor migration summary screen error to accept arbitrary react
* Refactor failed file presentation to show all failed files and the corresponding failure reason in a list
The design is a little bit offensive right now, we definitely want to iterate on this
> CHET-384: render failed files and their reasons

- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
* If 100 errors are seen we tell the user that it's the minimum number of errors
* Instructions on how to resolve fs failures
* Manual copy _OR_ restart migration
* Correct learn more link for errors on MigrationTransferPage
> CHET-385: Additional FS migration failure content

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/MigrationEndpoint.kt
- api/src/main/kotlin/com/atlassian/migration/datacenter/api/db/DatabaseMigrationEndpoint.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/restore/SsmPsqlDatabaseRestoreService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/ssm/SSMApi.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/restore/SsmPsqlDatabaseRestoreServiceTest.java
- frontend/package.json
- frontend/src/main/dc-migration-assistant-fe/api/db.ts
- frontend/src/main/dc-migration-assistant-fe/components/db/DatabaseMigration.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationDetailsProps.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationErrorSection.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
- frontend/src/main/dc-migration-assistant-fe/components/warning/WarningStage.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
- frontend/yarn.lock
* Create `/migration/db/logs `GET` REST endpoint to fetch the end result when we have finished the DB restore. Example responses:
```
{
"consoleUrl": "https://console.aws.amazon.com/s3/buckets/atl-migrationbucket-abrokes-migration-helper/trebuchet-ssm-document-logs/6cc3f383-a916-4fdd-b23b-6b614e642944/i-08f9fa6be33226139/awsrunShellScript/restoreDatabaseBackupToRDS/",
"errorMessage": ""
}
```
* Display `SectionMessage` when there was an error in the DB migration and provide link to reach the AWS S3 Console with the `stdout` and `stderr` files.
* We also get first 8000 characters of the error but to keep the designs simple we've decided to not show it in the interface.
> CHET-355: Add SSM url to the output logs

- frontend/package.json
- frontend/src/main/dc-migration-assistant-fe/components/Home.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/auth/AuthenticateAWS.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationErrorSection.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
- frontend/yarn.lock
* Formatted the landing page closer to our design specification
* Added lozenges for the requirements
* Added spinner (instead of `...`) when we are fetching the status for each requirement
* Added same formatting for the Auth page
* Updated the title to `Jira Data Center Migration App`
The landing page
Spinners while loading
Auth page formatting
> CHET-402: Update the Home design

- core/src/main/java/com/atlassian/migration/datacenter/core/fs/captor/JiraIssueAttachmentListener.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/captor/JiraIssueAttachmentListenerTest.java
- jira-plugin/pom.xml
* Use `AttachmentStore` to get attachment thumbnails
* Add `gaFeatures` spring profile to default amps run
> CHET-406: Capture attachment thumbnails

- core/src/main/java/com/atlassian/migration/datacenter/core/fs/captor/AttachmentSyncManager.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/captor/DefaultAttachmentPathCaptor.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/captor/FileSyncRecord.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/captor/DefaultAttachmentPathCaptorTest.java
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- jira-plugin/src/main/resources/atlassian-plugin.xml
- spi/src/main/java/com/atlassian/migration/datacenter/dto/FileSyncRecord.java
- spi/src/main/java/com/atlassian/migration/datacenter/dto/Migration.java
* Implement DTO class for capturing paths "listened to" during the FS copy
* Associate these paths with the current migration
* Implement and test, storing and fetching these paths
> CHET-396: persist listened files

- core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/listener/JiraIssueAttachmentListener.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/listener/JiraIssueAttachmentListenerTest.java
- frontend/src/main/dc-migration-assistant-fe/api/fs.ts
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
* Fix some null dereferences in transfer page
* Drop thumbnailable filter from issue listener - it was causing NPE's and missing the thumbnails
> Transfer page and fs listener bugfixes

- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/infrastructure/InfrastructureDeploymentStatus.kt
This was breaking the deployment status endpoint because sometimes the stack status reason is null and kotlin wasn't allowing the null. Since this is called from java code I decided it's better to allow null than to try change it to not be null as this structure is only really used by the API and it is not serialised by jackson when null
> Allow deployment status reason to be null

- frontend/src/main/dc-migration-assistant-fe/components/shared/CancelButton.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPageActions.tsx
- frontend/src/main/dc-migration-assistant-fe/components/warning/WarningStage.tsx
Fixed padding between navigation buttons including the navigation buttons on the following routes:
```
- auth (step 1 of 6)
- provision (step 2 of 6)
- provision/status 
- fs (step 3 of 6)
- warning (step 4 of 6)
- db (step 5 of 6)
```
New padding between navigation buttons now rendered like so:
> CHET-412: Fix padding between navigation buttons

- frontend/src/main/dc-migration-assistant-fe/components/aws/AwsRoutes.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/ProvisioningStatusPage.tsx
When transitioning from step `Step 2 of 6: Deploy on AWS` by selecting the `Deploy` button the subsequent page is scrolled to the bottom. This fix ensures the subsequent scrolls to the top on load.
> CHET-323: Scroll to top of page on page transitions

- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/S3FinalFileSync.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/fs/S3FinalFileSyncTest.kt
* New class which uses attachment sync manager to get listened files
* Use S3Uploader to upload them all to S3
* Create instance during Final sync phase (DB migration)
* Run upload
* I wanted to make this a service and export it as a bean injecting the Uploader is difficult as it depends on the report and `S3Config`. I tried picking apart the uploader but it's a bit of a rabbit hole so I'm just going to construct it at migration time.
* A good future refactor would be to decouple the S3 config, S3 uploading, and S3 reporting from the `S3Uploader` implementation
> CHET-428: Helper for uploading all captured paths to S3

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/db/DatabaseMigrationEndpoint.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/util/MigrationRunner.java
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalFileSync.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncRunner.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncService.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalFileSyncTest.kt
* Implement scheduled job for running final file sync
* Start scheduled job in DB API endpoint
* This is not very well integrated with the state machine, however I think that can come as a follow-up once the final sync is completed end-to-end
* I'm thinking of changing the name and path of the DB endpoint so it encompasses both the DB migration and the fs final sync. Maybe `FinalSyncEndpoint` or something like that. Any thoughts?
> CHET-409: run file final sync during offline period

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/CfnApi.java
- frontend/src/main/dc-migration-assistant-fe/api/provisioning.ts
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickstartRoutes.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/asi/ASIConfiguration.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/asi/ExistingASIConfiguration.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
* Hoist ASI loading into parent ASI Configuration page
* Render stack name along with stack prefix in prefix selection drop-down
* Optimise `CfnApi#listStacks` to only list active stacks
* Wire up ASI configuration page to ASI description API endpoint
> CHET-433: wire up asi selector to api

- templates/migration-stack/Makefile
- templates/migration-stack/migration-helper.yml
- templates/migration-stack/pkg/migration-helper.yml.src
Tests using a `make createstack` show that the migration buckets are now created with the correct public access settings:
> CHET-185: Lock down migration bucket

- templates/utils/cfn_parameters/README.md
- templates/utils/cfn_parameters/parameters_gen.py
- templates/utils/cfn_parameters/requirements.txt
Write a parameters YAML string to stdout with contents - 
```
ParameterGroups:
- Label:
default: Jira setup
Parameters:
- JiraProduct
- JiraVersion
- Label:
default: Cluster nodes
Parameters:
- CloudWatchIntegration
- ClusterNodeInstanceType
- ClusterNodeMax
- ClusterNodeMin
- ClusterNodeVolumeSize
- DeploymentAutomationRepository
- DeploymentAutomationBranch
- DeploymentAutomationPlaybook
- DeploymentAutomationCustomParams
- DeploymentAutomationKeyName
- Label:
default: Database
Parameters:
- DBEngine
- DBInstanceClass
- DBIops
- DBMasterUserPassword
- DBMultiAZ
- DBPassword
- DBStorage
- DBStorageEncrypted
- DBStorageType
- Label:
default: Networking
Parameters:
- InternetFacingLoadBalancer
- CidrBlock
- KeyPairName
- SSLCertificateARN
- Label:
default: DNS (Optional)
Parameters:
- …
```
> CHET-424: script parameters generation using python

- frontend/src/main/dc-migration-assistant-fe/components/db/DatabaseMigration.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPageActions.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
1. Changes step numbers to include the 8th step
2. Changes db sync to final sync
3. Updates start button text for db sync only (`Sync Now`, `Start` for the rest of the migration transfer stages) using the `nullish` operator
Start button text now reads as Sync now
> CHET-420: Update warning page text

- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickStartDeploy.test.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickStartDeploy.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickstartRoutes.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/asi/ASIConfiguration.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/asi/ExistingASIConfiguration.tsx
* Hoist deployment mode to parent of quickstart and ASI configuration component
* Share deployment mode with quickstart form
* Add standalone quickstart parameters file to frontend
* Load quickstart parameters based on deployment mode
> CHET 434: change quickstart form based on deployment option

- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/asi/ExistingASIConfiguration.tsx
There was a bug where the stack name was included as part of the prefix. Now we just get the sweet prefix
> CHET-427: only use prefix part of ASI select to feed quickstart form

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/aws/CloudFormationEndpoint.kt
- api/src/test/kotlin/com/atlassian/migration/datacenter/api/aws/CloudFormationEndpointTest.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceTest.java
- frontend/src/main/dc-migration-assistant-fe/api/provisioning.ts
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickStartDeploy.tsx
- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/infrastructure/ApplicationDeploymentService.kt
- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/infrastructure/ProvisioningConfig.kt
- spi/src/test/kotlin/com/atlassian/migration/datacenter/spi/infrastructure/ProvisioningConfigTest.kt
* Implement ability to deploy with-vpc or standalone quickstart in backend
* Expose configurable deployment via API
* Call API with deployment mode depending on user choice in ASI configuration screen
* Currently, the JSON is not deserializing nicely into the `ProvisioningConfig` expected by the backend. Will probably have to work on this next week.
> CHET-435: deploy standalone or with vpc

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/FinalSyncEndpoint.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationService.java
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncService.kt
- frontend/src/main/dc-migration-assistant-fe/api/final-sync.ts
- frontend/src/main/dc-migration-assistant-fe/components/db/DatabaseMigration.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationErrorSection.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
* Rename endpoint class
* Update endpoint paths
* Update frontend calls of endpoint
* Fix some bugs with aborting the final sync
* Fix some incorrect logging strings
* Fix bug with missing DB status to i18n mapping
> CHET 448: Refactor db endpoint to be "final sync endpoint"

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/aws/AWSResourceCleanupEndpoint.kt
- api/src/test/kotlin/com/atlassian/migration/datacenter/api/aws/AWSResourceCleanupEndpointTest.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationInfrastructureCleanupService.kt
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/infrastructure/InfrastructureCleanupStatus.kt
- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/infrastructure/MigrationInfrastructureCleanupService.kt
* Implement interface for cleaning up migration infrastructure
* Implement api for starting migration infrastructure cleanup
* Implement dummy cleanup service
API being called from postman
Cleanup being logged in Jira logs
> CHET-457: delete resources endpoint

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArchivalService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArtifactS3UploadService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/restore/SsmPsqlDatabaseRestoreService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/captor/AttachmentSyncManager.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/captor/DefaultAttachmentSyncManager.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/jira/listener/JiraIssueAttachmentListener.java
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncRunner.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncService.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/SqsQueueWatcher.kt
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArchivalServiceTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArtifactS3UploadServiceTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationServiceIT.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationServiceTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/restore/SsmPsqlDatabaseRestoreServiceTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/captor/DefaultAttachmentSyncManagerTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/jira/listener/JiraIssueAttachmentListenerTest.java
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncServiceTest.kt
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
Ok, this PR got a little bloated and now it contains -
1. A mechanism to stop attachment listener in FINAL_SYNC_WAIT stage. This is necessary as we don't want to keep listening to file records in case the migration fails and a user does not cancel/clean up the migration
2. Refactored the object graph/construction of Database migration service. We don't need to create both the service and the callback in the database service. Instead, we create the archive/upload/restore service with the callbacks
3.  We read the file system record collection for a given migration and using this, determine the number of files that have been uploaded to S3.
> Chet 464 final sync uploaded count

- templates/migration-stack/migration-helper.yml
- templates/migration-stack/pkg/migration-helper.yml.src
SSM commands were trying to write log files to a directory that was not being created. This PR 
1. Creates a log directory under `/var/log/atlassian/dc-migration-assistant`
2. Refers to the above directory to store sync, error and db restore logs
> CHET-442: Create log directory if it does not exist.

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/migrationStack/ASIExportKeys.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/migrationStack/MigrationStackInputGatheringStrategy.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/migrationStack/MigrationStackInputGatheringStrategyFactory.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/migrationStack/QuickstartStandaloneMigrationStackInputGatheringStrategy.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/migrationStack/QuickstartWithVPCMigrationStackInputGatheringStrategy.kt
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceTest.java
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/MigrationBucketCleanupServiceTest.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/migrationStack/MigrationStackInputGatheringStrategyFactoryTest.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/migrationStack/QuickstartStandaloneMigrationStackInputGatheringStrategyTest.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/migrationStack/QuickstartWithVPCMigrationStackInputGatheringStrategyTest.kt
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- spi/src/main/kotlin/com/atlassian/migration/datacenter/dto/MigrationContext.kt
* Move migration stack related kotlin code to new package within `core/aws/infrastructure`
* Clean up some duplication between the parameter discovery mechanisms
* Implement factory that can provide a parameter strategy based on deployment mode
* Store deployment mode in the deployment context
* Update quickstart deployment to use the factory to get a strategy for the current deployment mode
> CHET-451: integrate standalone migration stack deployment

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceTest.java
Use S3 URL in Backend instead of github URL
> CHET-442: Fix S3 url in CFN deployment service

- .github/CODEOWNERS
- jira-e2e-tests/.env
docker-compose fails when it is run without passing a build-arg or an env variable specifying the `jira_version` based docker image to pull. Adding a .env and defaulting to latest will ensure that current workflows continue to work
> no-issue: make compose pick up latest jira dockerimage by default

- .github/workflows/mvn_test.yml
- pom.xml
Add jacoco to parent pom. No coverage limit has been set for the project. 
This is only plugged in with the unit test phase and not with integration tests
> no-issue: add jacoco

- .github/workflows/migration_template_uploader.yml
- templates/migration-stack/pkg/migration-helper.yml.src
There is potentially an issue where `migration-helper.yml` is not re-generated and uploaded when changes are made to `migration-helper.yml.src`. To help root cause this we now, output the `md5sum` and contents of `migration-helper.yml` when generated.
Testing shows that changes made to `migration-helper.yml.src` result in different md5's being generated between runs
*run 1*
`migration-helper.yml md5 is: [413c23a5b406f1e35ed330c8d2ebf076  ./templates/migration-stack/migration-helper.yml]`
*run 2*
`migration-helper.yml md5 is: [014afb645fb675564ebe1dfa0ab76384  ./templates/migration-stack/migration-helper.yml]`
*run 3*
`migration-helper.yml md5 is: [ab3d4dd6e3809563df24d3279a9546ea  ./templates/migration-stack/migration-helper.yml]`
This suggests that a new version of `migration-helper.yml` …
> Output md5 and contents for migration-helper.yml

- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/MigrationStage.kt
* Refactor migration stage so that retry transitions are not special cases
* Implement cycle detection in is after
* Add transition from FINAL_SYNC_ERROR to DB_MIGRATION_EXPORT and FINAL_SYNC_WAIT
> CHET-528: Add retry transition for final sync

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/aws/CloudFormationEndpoint.kt
- api/src/test/kotlin/com/atlassian/migration/datacenter/api/aws/CloudFormationEndpointTest.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/CloudformationDeploymentService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentServiceTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/MigrationHelperDeploymentServiceCleanupTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceCleanupTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceTest.java
- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/infrastructure/DeploymentService.kt
1. Creates a method in the interface to clear persisted stack details 
2. Invokes the above method from a `reset` API call
3. Updates tests and removes unnecessary stubings as we do not call reset stack outputs before deploying the template
The error column is not flushed as part of this.
> Chet 525 clear context

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/FinalSyncEndpoint.kt
- api/src/test/kotlin/com/atlassian/migration/datacenter/api/FinalSyncEndpointTest.kt
- pom.xml
* New endpoints: `/migration/final-sync/retry/{db,fs}`
* Only does retry if state is `FINAL_SYNC_ERROR`
* Each will move the state machine to the starting state for the respective process then start the process.
> CHET-526: independent final sync processes from API

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/FinalSyncEndpoint.kt
- api/src/test/kotlin/com/atlassian/migration/datacenter/api/FinalSyncEndpointTest.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationService.java
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncService.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncServiceTest.kt
* Use deadletter queue as measure of errors for fs final sync
TODO: when retrying the fs migration, move everything from the DLQ to the migration queue
> CHET-527: track final sync fs errors

- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/SqsQueueWatcher.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/fs/captor/SqsQueueWatcherTest.kt
From the ticket:
>These things happen in the state machine during the final sync
>
>   The FS sync tries to transition to VALIDATE from FINAL_SYNC_WAIT when it completes
>
>   The DB migration makes assertions about what state of the state machine it is in and does transitions
>
>Therefore to successfully “retry” each operation individually (under current implementation, before starting this story)
>
>  The state must be FINAL_SYNC_WAIT when the FS sync finishes and cannot change after entering that state (outside of from the FS final sync itself transitioning to VALIDATE)
>
>  The state must be DB_MIGRATION_EXPORT when the DB migration starts and must not be changed underneath it until it completes
>
>This can lead to issues when both operations are restarted. Consider this:
>
>  FS sync …
> CHET-529: [core] ensure state is correct when completing FS final sync

- core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/SqsApi.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/SqsApiImpl.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/exceptions/AwsQueueError.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncRunner.kt
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
When a message fails to be processed from the migration queue 5 times, it will be pushed to the dead letter queue. We use this queue to measure failures for the final file sync. When retrying, we empty the queue so that we can start fresh. Any entries in that queue will be re-uploaded anyway when retrying
> CHET-534: clear dead letter queue

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/restore/SsmPsqlDatabaseRestoreService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/ssm/SuccessfulSSMCommandConsumer.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/restore/SsmPsqlDatabaseRestoreServiceTest.java
- jira-plugin/pom.xml
This prevents SSMApi consumer to fail after 100 seconds even when the command is still running.
> CHET-503: Allow SSM API execution without upper boundary

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/ssm/SuccessfulSSMCommandConsumer.java
Currently seeing this as part of a migration 
```
2020-06-25 04:02:05,443+0000 Caesium-2-3 DEBUG ServiceRunner     [c.a.m.d.c.aws.ssm.SuccessfulSSMCommandConsumer] Checking delivery of s3 sync ssm command. Attempt 1
2020-06-25 04:02:05,443+0000 Caesium-2-3 DEBUG ServiceRunner     [c.a.m.d.c.aws.ssm.SSMApi] getting status of command 93d58ca3-518d-4bcb-b151-439d84558902 on instance i-0c53b7aed246b7d8a
2020-06-25 04:02:05,487+0000 Caesium-2-3 DEBUG ServiceRunner     [c.a.m.d.c.aws.ssm.SuccessfulSSMCommandConsumer] Command does not exist - maybe it hasn't reached the EC2 instance yet. Will continue retrying
2020-06-25 04:02:15,487+0000 Caesium-2-3 ERROR ServiceRunner     [c.a.scheduler.core.JobLauncher] Scheduled job with ID 'com.atlassian.migration.datacenter.fs.S3UploadJobRunner2' failed …
```
> CHET-503: Fix null pointer exception when checking command status

- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/asi/ASIConfiguration.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
* Don't render text input when no ASI's
* Show text explaining why
* Allow transition to next page
> Don't render any user input in ASI config step if there are no ASI's in chosen region.

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/application/ApplicationPropertiesEndpoint.kt
- api/src/test/kotlin/com/atlassian/migration/datacenter/api/application/ApplicationPropertiesEndpointTest.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/application/ApplicationConfiguration.java
- core/src/main/java/com/atlassian/migration/datacenter/core/application/JiraConfiguration.java
- frontend/src/main/dc-migration-assistant-fe/api/application.ts
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickStartDeploy.tsx
- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/quickstartToAtlaskit.tsx
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantOsgiImportConfiguration.java
* added `GET` `/application/properties` endpoint - currently returning just the application version (already in Postman)
* set the version as a default for the `JiraVersion` field
* make the field `disabled` so customers will always deploy the same version as they are currently running
> CHET-535: Prefill application version and disable the field

- core/src/main/java/com/atlassian/migration/datacenter/core/fs/DirectoryStreamCrawler.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/DirectoryStreamCrawlerTest.java
The `export` folder can contain a huge amount of data - by default there is a scheduled daily job that saves XML export from the database. On a large instance, it means 7.5 GB daily.
> CHET-548: Ignore the export folder when running initial sync to S3

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/DatabaseClientTools.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/DefaultDatabaseExtractorFactory.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/PostgresClientTooling.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/PostgresExtractor.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/UnSupportedDatabaseExtractor.kt
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationServiceIT.java
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/db/PostgresClientToolingIT.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/db/PostgresClientToolingTest.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/db/PostgresExtractorIT.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/db/PostgresExtractorTest.kt
- frontend/src/main/dc-migration-assistant-fe/components/Home.tsx
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
extract `pg_dump` availability and version checks so that they can be run independently.
> CHET-556: Decouple pg_dump availability check logic

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/AllowAnyTransitionMigrationServiceFacade.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantProfileSpecificConfiguration.java
- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/MigrationService.kt
Return AWS migration service from the bean configuration.
Remove a few unused parameters from the service
> Chet 558 inject non facade AWS migration service bean

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationEndpoint.kt
- frontend/src/main/dc-migration-assistant-fe/api/fs.ts
- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
* Create a stub FS retry endpoint which will log the retry has been attempted
* Wire up the endpoint to the frontend
> CHET-558/568: Call FS Stub retry endpoint from FS UI

- frontend/src/main/dc-migration-assistant-fe/components/shared/ErrorFlag.tsx
- frontend/src/main/dc-migration-assistant-fe/components/stage/Validation.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
Above screenshot shows both requests from one button click (Failing because Jira not running).
One concern that I have is that the migration cleanup will fail and we have no way to report that to the user. However, since the cleanup is a long-running task, we should not show that the cleanup failed here
> CHET-557: Auto cleanup migration infrastructure when finishing migration

- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
Error message now reflect image below. Green boxes indicate a wording change. The resolution text description has also been lifted out from the collapsible panel, meaning it will always be shown.
> CHET-559: Minor updates to error message panel

- core/src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/AllowAnyTransitionMigrationServiceFacade.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/AwsMigrationServiceWrapper.kt
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationServiceTest.java
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantProfileSpecificConfiguration.java
- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/MigrationService.kt
Create a kotlin wrapper implementation for AWS migration service.
Implement a method to transition to any error stage, not just the generic `ERROR` stage
Transitions error stage transition from file system migration service to `FS_MIGRATION_ERROR`
> Chet 558 stage specific error

- core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3MultiPartUploader.java
* Smaller chunk size to avoid write timeout
* Fix Java 11 and 8 interoperability (the problem is API change for `ByteBuffer` in Java 9 https://jira.mongodb.org/browse/JAVA-2559)
> CHET-516: Fix Multipart uploader

- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferProgress.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/Progress.ts
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
Changes in green boxes:
- Introduce a new `Continue` button 
- Update resolution text 
When `Continue` is selected the user is taken to the next page in the migration flow...
> CHET-560: Allow users to continue with migration despite failed file uploads

- frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/ProvisioningStatusPage.tsx
- frontend/src/main/dc-migration-assistant-fe/components/final-sync/FinalSync.tsx
- frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.test.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferProgress.tsx
- frontend/src/main/dc-migration-assistant-fe/components/shared/Progress.ts
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
Use conditional rendering to determine whether the `Ignore and continue` button is rendered for a failed migration stage. For the puproses of this PR this button will only be rendered if there is an assets file upload failure i.e `Step 4 of 7: Copy Content`
- When the `Ignore and continue` button is selected the user is taken to `Step 5 of 8`...
> CHET-560: Allow users to continue with migration

- frontend/src/main/resources/i18n/dc-migration-assistant.properties
> The blue button should say "Close the migration app" , though
> Also typo "Performa"
> no-issue: [frontend] fix typos in validation page

- frontend/src/main/dc-migration-assistant-fe/components/Home.tsx
Create a DC-license requirement to the per-requisites before a customer starts a migration. This will be done as a static text.
> CHET-580: Update landing page

- filesystem-processor/src/main/resources/bootstrap.properties
- templates/migration-stack/pkg/migration-helper.yml.src
Adds the ability to run multiple migration stacks in a region by including a `{StackName}-helper` prefix to parameter store keys
See: https://cloud.spring.io/spring-cloud-static/spring-cloud-aws/2.1.0.RELEASE/single/spring-cloud-aws.html#_integrating_your_spring_cloud_application_with_the_aws_parameter_store
> CHET-591: Add a prefix to ssm parameter lookup names

- frontend/src/main/dc-migration-assistant-fe/components/stage/Validation.tsx
- frontend/src/main/resources/i18n/dc-migration-assistant.properties
This is intended to prepare users so they don't panic when following the link to Jira and seeing a 502 or 503 error
> CHET-596: include warning about slow jira start time in validation page

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/FinalSyncEndpoint.kt
- api/src/main/kotlin/com/atlassian/migration/datacenter/api/aws/CloudFormationEndpoint.kt
- api/src/main/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationEndpoint.kt
Skip websudo for status endpoints, which avoids the sudo redirect during migration. The status endpoints should never return anything sensitive. With this in place the admin will only be prompted a password after the transition to the next stage.
> CHET-606: Skip websudo for status endpoints

- frontend/src/main/dc-migration-assistant-fe/components/warning/WarningStage.tsx
When clicking "Next" on the offline warning page it would cause a full-page reload and thus redirect back to itself. This is because when the page is loaded fresh, it tries to send you to the "current" page for where you are in the migration. Because there is no state transition when doing this "next", we are in the same state and thus load the same page.
We get around this by using a client-side redirect instead of a full-page reload. The ASI configuration -> deploy cluster has the same anomaly in that there are two pages for the same state but it was already using a client-side redirect instead of a full-page reload so never fell victim to this behaviour.
> no-issue: Fix self-redirect when moving from offline warning to final sync

- CONTRIBUTING.md
updating these to reflect our new CLA system as we've moved away from DocuSign 🙂
> updating CLA links to use new CLA system

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/FinalSyncEndpoint.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/CloudformationDeploymentService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentServiceTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/CloudformationDeploymentServiceTest.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentServiceTest.java
- spi/src/main/kotlin/com/atlassian/migration/datacenter/dto/MigrationContext.kt
- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/MigrationStage.kt
- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/infrastructure/InfrastructureDeploymentState.kt
- spi/src/test/kotlin/com/atlassian/migration/datacenter/spi/MigrationStageTest.kt
* Refactor deployment status API result to come from DB
* Refactor backend polling of cloudformation deployment status to commit result to db
* Refactor migration stage `isAfter` logic to exclude retry paths
* This was necessary because we use the current migration stage to determine how to respond to a query for deployment status. e.g. if we check the migration stack deployment status from the `FS_MIGRATION_COPY` stage (or any stage in the future), we return `CREATE_COMPLETE` because to get to that stage you need a successful migration stack deployment
> CHET-608: consistent deployment state

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationEndpoint.kt
- api/src/test/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationEndpointTest.kt
- api/src/test/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationProgressEndpointTest.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/RetryFailedFileMigration.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/fs/RetryFailedFileMigrationTest.kt
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- jira-plugin/src/main/resources/templates/dc-migration-assistant.soy
* Move abort of file system migration from file migration API endpoint to new FS migration Retry service
* Before uploading the failed files, the service will abort the running FS migration
* Note: Is this the right thing to do? We were doing it before but in my opinion, we shouldn't allow retry while the FS migration is in progress. This is a hypothetical scenario but better safe then sorry imo.
* Move retry transition `FS_MIGRATION_ERROR` ➡️ `FS_MIGRATION_COPY` to file system retry service
* Add missing transition `FS_MIGRATION_COPY` ➡️ `FS_MIGRATION_COPY_WAIT` to file system retry service
> CHET-638/9: Move abort and state transition from file migration endpoint to fs partial retry service

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/MigrationEndpoint.kt
- api/src/test/kotlin/com/atlassian/migration/datacenter/api/MigrationEndpointTest.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/AllowAnyTransitionMigrationServiceFacade.java
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/ReuseInfrastructureAWSMigrationService.kt
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/AwsMigrationServiceWrapper.kt
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java
- jira-e2e-tests/helpers/run-local
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
- jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantProfileSpecificConfiguration.java
- spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/MigrationService.kt
* Create beans which will bypass cleanup of infra at end of migration
* Create beans which will reset migration to FS copy stage at end of migration
* Add configuration to `jira-e2-tests/helpers/run-local` script that runs the app in a mode which retains infrastructure
Companion documentation to this feature: https://aws-partner.atlassian.net/wiki/spaces/DOA/pages/395903049/HOWTO+retain+infrastructure+between+migrations+when+testing+Trebuchet
> CHET-634: re-use provisioning

- .github/workflows/mvn_test.yml
- jira-e2e-tests/cypress/integration/e2e_full_migration.ts
- jira-e2e-tests/cypress/integration/landing_page.ts
- jira-e2e-tests/cypress/package.json
- jira-e2e-tests/cypress/support/index.d.ts
- jira-e2e-tests/cypress/support/index.js
- jira-e2e-tests/cypress/support/jira.ts
- jira-e2e-tests/cypress/support/pages/AwsAuthPage.ts
- jira-e2e-tests/cypress/support/pages/FileSystemMigration.ts
- jira-e2e-tests/cypress/support/pages/FinalSync.ts
- jira-e2e-tests/cypress/support/pages/LandingPage.ts
- jira-e2e-tests/cypress/support/pages/ProvisioningPage.ts
- jira-e2e-tests/cypress/support/pages/QuickstartForm.ts
- jira-e2e-tests/cypress/support/pages/SelectAsiPage.ts
- jira-e2e-tests/cypress/support/pages/ValidationPage.ts
- jira-e2e-tests/cypress/support/waiters.ts
- jira-e2e-tests/cypress/yarn.lock
- jira-e2e-tests/docker-compose.yml
* Add Github Actions for the end to end test
* Expose screenshots and videos from the docker container
* Split the large e2e test into separate functions (so we can see what failed)
* Hide typed passwords
* Re-login after long-running actions (provisioning, fs sync)
* Handle failed FS migrated files (e.g. analytics log)
* Increase timeouts to reflect slower Actions environment
> CHET-627: End to end test stabilisation && GitHub Actions

- api/pom.xml
- build-utils/pom.xml
- core/pom.xml
- filesystem-processor/pom.xml
- frontend/pom.xml
- jira-plugin/pom.xml
- pom.xml
- spi/pom.xml
Original `1.1.0` release was a bad cut. 
Creating a new release and tag for `1.1.1`.
> DCD-1070: Bump release version

- .github/workflows/mvn_test.yml
We should be naming our release branches `releases/XY` and for them we should run the e2e test as well.
Ideally we should automate our release process further.
> NONE: Add e2e tests for releases/* branches

- api/pom.xml
- build-utils/pom.xml
- core/pom.xml
- filesystem-processor/pom.xml
- frontend/.env
- frontend/pom.xml
- jira-e2e-tests/README.md
- jira-e2e-tests/jira/Dockerfile
- jira-plugin/pom.xml
- pom.xml
- spi/pom.xml
Amazon changed the default branch for the quicksarts to `main` 🥳 However we didn't correct the URL of our quickstarts so I've done that now. We also released a new version to marketplace so the version has been bumped up (I accidentally skipped a version).
> Hotfix update quickstart GitHub url

- api/src/main/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationEndpoint.kt
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java
- core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncRunner.kt
- core/src/test/kotlin/com/atlassian/migration/datacenter/core/fs/captor/S3FinalSyncRunnerTest.kt
The bug has caused final filesystem migration to fail in second migration run. We never changed the value of `isRunning` and the Runner is instantiated once when we are wiring the classes together.
I have also created a safeguard in case the migration would somehow fail, so the class listens to `MigrationResetEvent` and reset itself in case it still is marked as running. 
The `DCD-1149-downgrade-postgresql` fixes the builds so I have rebased the branch on top of it and will retarget master after https://github.com/atlassian-labs/dc-migration-assistant/pull/425 is merged.
> Dcd 1136: Reset FS migration state after finishing the migration

- pom.xml
This prevented maven release plugin to push the tags when making release.
> NONE: Update the project SCM protocol

- .github/workflows/mvn_test.yml
- core/src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderTest.java
- jira-e2e-tests/cypress/integration/smoketest.ts
- pom.xml
---
This task grew a bit with many other failing tests so here is a full summary:
* Update `testcontainers` which was causing failures due to old version with no longer existing `ryuk` image tag
* Fix flaky s3 uploader test by inverting async dependencies so the assertion was in a background thread
* Fix smoke test which failed because DC Migration Assistant app was not visible in viewport in UPM
> Fix some failing tests

- .github/workflows/mvn_test.yml
- core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/CloudformationDeploymentService.java
- core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/CloudformationDeploymentServiceTest.java
The Java 11 unit tests were failing because `CloudformationDeploymentServiceTest#shouldCallHandleFailedDeploymentWhenDeploymentFails` was failing repeatedly. This test was relying on thread jittering to pass so I have refactored it so that it waits until the "deployment" is "completed" before checking the deployment as failed.
> DCD-1164: Fix java 11 Unit Tests

- pom.xml
This version bump fixes all of the XXE vulnerabilities currently associated with the code base except for this [one](https://github.com/atlassian-labs/dc-migration-assistant/security/code-scanning/272?query=ref%3Arefs%2Fheads%2Fdcd-1177-xml-external-entity)
At present there is no fix for this see [SNYK-JAVA-DOM4J-174153](https://snyk.io/vuln/SNYK-JAVA-DOM4J-174153)
> DCD-1177: XML External Entity (XXE) vulnrability fix

- .github/workflows/snyk_security.yml
- .github/workflows/snyk_security_master.yml
- .snyk
- api/.snyk
- core/.snyk
- filesystem-processor/.snyk
- filesystem-processor/pom.xml
- frontend/.snyk
- jira-plugin/.snyk
- spi/pom.xml
Add exemptions for vulnerabilities relating to transitive dependencies found in; jira-api, atlassian-plugin, webpack, aws sdk. An expiry is also set on these exemptions so that on the 3rd of July 2021 these will no longer be exempt and will need to be re-assessed
As part of this PR an additional Snyk Github action has been added for `master`. This scan will:
- Run everyday at midnight on`master` only
- Fail when any severe vulnerabilities are encountered, meaning action needs to be taken to keep master up to date from a security standpoint
> Additional vulnerability mitigation
