atlassian-labs/dc-migration-assistant

pom.xml, src/main/dc-migration-assistant-fe/components/App.tsx, src/main/dc-migration-assistant-fe/components/MigrationOverview.tsx, src/main/dc-migration-assistant-fe/components/aws/AwsRoutes.tsx, src/main/dc-migration-assistant-fe/components/aws/auth/AuthenticateAWS.tsx, src/main/dc-migration-assistant-fe/utils/RoutePaths.ts, src/main/dc-migration-assistant-fe/utils/api.ts, src/main/java/com/atlassian/migration/datacenter/api/aws/AWSGlobalInfrastructureEndpoint.java, src/main/java/com/atlassian/migration/datacenter/core/aws/GlobalInfrastructure.java, src/test/java/com/atlassian/migration/datacenter/api/aws/AWSGlobalInfrastructureEndpointTest.java, src/test/java/com/atlassian/migration/datacenter/core/aws/GlobalInfrastructureTest.java, wrm.d.ts
Introduces small endpoint to query all AWS regions for populating drop-downs in frontend.
=> Chet 92 - AWS region rest endpoint

templates/migration-stack/Makefile, templates/migration-stack/migration-helper.yml, templates/migration-stack/src/MigrationHelper/.ebextensions/remove_default_http_rule.config, templates/migration-stack/src/MigrationHelper/.ebextensions/storage_efs_mountfilesystem.config, templates/migration-stack/src/MigrationHelper/application.py, templates/migration-stack/src/MigrationHelper/cron.yaml
Documentation
https://aws-partner.atlassian.net/wiki/spaces/DOA/pages/73924645/Proposal+-+Migration+Helper+CloudFormation+Stack
=> Add migration stack template

src/main/java/com/atlassian/migration/datacenter/spi/statemachine/State.java
Implements very basic state model. I think this will require iteration as we figure out all the flows however my current assumptions are:
* `run()` is called by some state management service based on a user action (API call or click a button in UI)
* `readyToTransition()` is used by the state management service to determine if a request by the user to move to the next state can be honoured
* `nextState()` is used by the state management service to determine which state to transition to
=> CHET-123: Implement simple State interface

src/main/java/com/atlassian/migration/datacenter/api/aws/CloudFormationEndpoint.java, src/main/java/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationProgressEndpoint.java, src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java, src/main/java/com/atlassian/migration/datacenter/core/exceptions/InfrastructureProvisioningError.java, src/main/java/com/atlassian/migration/datacenter/core/exceptions/InvalidMigrationStageError.java, src/main/java/com/atlassian/migration/datacenter/spi/MigrationService.java, src/test/java/com/atlassian/migration/datacenter/api/aws/CloudFormationEndpointTest.java, src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java
1. Adds checked exceptions and sends appropriate response codes to client
2. Pulls object mapper instantiation to constructor
=> No issue general improvements

src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java, src/main/java/com/atlassian/migration/datacenter/spi/MigrationStage.java, src/test/java/com/atlassian/migration/datacenter/api/MigrationEndpointTest.java, src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java
This formalises the migration states based upon our whiteboarding a little while ago.
=> CHET-139: Formalise migration states

pom.xml, src/main/java/com/atlassian/migration/datacenter/api/aws/AWSAvailabilityZoneEndpoint.java, src/main/java/com/atlassian/migration/datacenter/core/aws/region/AvailabilityZoneManager.java, src/main/java/com/atlassian/migration/datacenter/core/aws/region/AvailabilityZoneService.java, src/test/java/com/atlassian/migration/datacenter/api/aws/AWSAvailabilityZoneEndpointTest.java
Adds the service to return the list of AWS Availability Zones for a region.  Returns 404 on an invalid region in the region config.
=> Adding in service to return AZ listing for a region with tests.

.github/workflows/mvn_test.yml
cache npm on CI for faster builds
=> no-issue: cache npm dependencies on CI

pom.xml, src/main/java/com/atlassian/migration/datacenter/core/application/ApplicationConfiguration.java, src/main/java/com/atlassian/migration/datacenter/core/application/DatabaseConfiguration.java, src/main/java/com/atlassian/migration/datacenter/core/application/DatabaseConfigurationXmlElement.java, src/main/java/com/atlassian/migration/datacenter/core/application/JiraConfiguration.java, src/main/java/com/atlassian/migration/datacenter/core/exceptions/ConfigurationReadException.java, src/main/java/com/atlassian/migration/datacenter/core/exceptions/UnsupportedPasswordEncodingException.java, src/test/java/com/atlassian/migration/datacenter/core/application/JiraConfigurationTest.java
InProgress - Testing wireup of spring components to verify if the osgi dependencies are wired up.
Note - Jackson brings in woodstox stax parser.
=> Chet 169 db config parse

src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java, src/main/java/com/atlassian/migration/datacenter/core/aws/auth/EncryptedCredentialsStorage.java, src/main/java/com/atlassian/migration/datacenter/core/util/EncryptionManager.java, src/test/java/com/atlassian/migration/datacenter/core/aws/auth/EncryptedCredentialsStorageTest.java, src/test/java/com/atlassian/migration/datacenter/core/util/EncryptionManagerTest.java
Harvests the encryption component of the encryption manager into its own singleton so that it can be used to encrypt the new database credentials.
These credentials will be needed by the migration stack.
=> CHET-202: harvest encryption

templates/migration-stack/migration-helper.yml, templates/migration-stack/pkg/migration-helper.yml.src
Just retrieves secret from secretsstore and syncs bucket containing the database dump.
Next steps (separate PR)
- Accept RDS endpoint as part of migration template
- exec psql restore from EFS to RDS 
- Monitor command output (?)
-- Follow pattern similar to FS restore
-- Check if psql has a progress option that can we could use?
=> Chet 189 ssm rds restore

templates/migration-stack/Makefile, templates/migration-stack/migration-helper.yml, templates/migration-stack/pkg/migration-helper.yml.src
* Adds bucket lifecycle policy to abort incomplete multipart uploads after 7 days
=> CHET-140: Add abort incomplete multipart upload lifecycle policy

jira-plugin/pom.xml
=> CHET-206: add api dependency to plugin

frontend/config/webpack.plugins.js, frontend/package.json, frontend/src/main/dc-migration-assistant-fe/components/App.tsx, frontend/src/main/dc-migration-assistant-fe/components/Home.tsx, frontend/src/main/dc-migration-assistant-fe/components/aws/auth/AuthenticateAWS.tsx, frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/__snapshots__/quickstartToAtlaskit.test.tsx.snap, frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/quickstartToAtlaskit.test.tsx, frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/quickstartToAtlaskit.tsx, frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx, frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx, frontend/src/main/resources/i18n/dc-migration-assistant.properties, frontend/yarn.lock
* Basic structure of components for migration page
* Props for changing the content strings
* Callbacks for updating the progress
=> CHET-231: Beginnings of generic migration page

frontend/src/main/dc-migration-assistant-fe/components/App.tsx, frontend/src/main/dc-migration-assistant-fe/components/Home.tsx, frontend/src/main/dc-migration-assistant-fe/components/db/DatabaseMigration.test.tsx, frontend/src/main/dc-migration-assistant-fe/components/db/DatabaseMigration.tsx, frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.test.tsx, frontend/src/main/dc-migration-assistant-fe/utils/RoutePaths.ts, frontend/src/main/resources/i18n/dc-migration-assistant.properties
Still needs callback implementation. Includes basic test infrastructure for the shared component.
=> CHET-42: DB migration

core/src/main/java/com/atlassian/migration/datacenter/core/aws/ssm/SSMApi.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/ssm/SuccessfulSSMCommandConsumer.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/download/s3sync/S3SyncFileSystemDownloadManager.java, frontend/src/main/dc-migration-assistant-fe/api/fs.ts, frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx, frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx, frontend/src/main/dc-migration-assistant-fe/utils/api.ts
Depends on #127 
* Calls fs status api
* Updates UI when data is there
Note: There is a bug and the "downloaded files" lags the actual files migration by a bit. This will be a follow up.
=> CHET-227: Update FS migration page with fs migration data

README.md, core/src/main/java/com/atlassian/migration/datacenter/core/fs/download/s3sync/S3SyncCommandStatus.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/download/s3sync/S3SyncFileSystemDownloadManager.java, core/src/test/java/com/atlassian/migration/datacenter/core/fs/download/s3sync/S3SyncFileSystemDownloadManagerTest.java, frontend/src/main/dc-migration-assistant-fe/api/fs.ts, frontend/src/main/dc-migration-assistant-fe/api/migration.ts, frontend/src/main/dc-migration-assistant-fe/components/db/DatabaseMigration.tsx, frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx, frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.test.tsx, frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferPage.tsx, frontend/src/main/dc-migration-assistant-fe/components/shared/Progress.ts, frontend/src/main/dc-migration-assistant-fe/components/shared/StartMigrationPhase.tsx, frontend/src/main/resources/i18n/dc-migration-assistant.properties
* Get errors from `failedFiles` of result
* Show number of failed files
* Show all unique reasons for file failure
* Render in error section message
=> CHET-256: surface fs page errors

frontend/.eslintrc.js, frontend/src/main/dc-migration-assistant-fe/api/migration.ts, frontend/src/main/dc-migration-assistant-fe/components/Home.tsx, frontend/src/main/resources/i18n/dc-migration-assistant.properties
This is a short-term workaround to allow us to continue with an in-progress migration.This will aid end-to-end testing.
=> CHET-266: Add ability to continue with a migration after started.

frontend/package.json, frontend/src/main/dc-migration-assistant-fe/components/App.tsx, frontend/src/main/dc-migration-assistant-fe/components/warning/WarningStage.tsx, frontend/src/main/dc-migration-assistant-fe/utils/RoutePaths.ts, frontend/src/main/resources/i18n/dc-migration-assistant.properties, frontend/yarn.lock
Modal approach for comparison - https://github.com/atlassian-labs/dc-migration-assistant/compare/CHET-312-display-modal
Screenshot
=> CHET-315: Add warning page

core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseUploadStageTransitionCallback.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentService.java, core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationServiceTest.java, core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentServiceTest.java, templates/migration-stack/migration-helper.yml, templates/migration-stack/pkg/migration-helper.yml.src
These bugs were found while testing the migration end-to-end via the UI.
* State transitions during the DB migration were incorrect and duplicated
* Migration stack had some syntax errors
=> CHET-273: Migration stack bugfixes; DB transfer bugfixes

frontend/src/main/dc-migration-assistant-fe/stage/Validation.tsx
=> CHET-321: make validation href open instance url link in a new page

frontend/src/main/dc-migration-assistant-fe/api/migration.ts
This will make it easier to show the error message on the new error screen.
=> CHET-23: add type for migration summary result

frontend/package.json, frontend/src/main/dc-migration-assistant-fe/components/aws/auth/AuthenticateAWS.test.tsx, frontend/src/main/dc-migration-assistant-fe/components/aws/auth/AuthenticateAWS.tsx, frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/quickstartToAtlaskit.tsx, frontend/yarn.lock
If value is not provided validation text appears
=> CHET-358: make keypair field required

frontend/package.json, frontend/src/main/dc-migration-assistant-fe/api/migration.ts, frontend/src/main/dc-migration-assistant-fe/components/aws/auth/AuthenticateAWS.tsx, frontend/src/main/dc-migration-assistant-fe/components/shared/CancelModal.tsx, frontend/src/main/resources/i18n/dc-migration-assistant.properties, frontend/yarn.lock
Will be followed with the cancel button -> reset migration integration
=> CHET-209: Create a simple modal

jira-plugin/pom.xml, pom.xml
=> CHET-387: Update plugin description visible on UPM page

api/src/main/kotlin/com/atlassian/migration/datacenter/api/MigrationEndpoint.kt, core/src/main/java/com/atlassian/migration/datacenter/core/application/ApplicationConfiguration.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/AllowAnyTransitionMigrationServiceFacade.java, core/src/test/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationServiceTest.java, frontend/.eslintrc.js, frontend/src/main/dc-migration-assistant-fe/api/migration.ts, frontend/src/main/dc-migration-assistant-fe/components/Home.test.tsx, frontend/src/main/dc-migration-assistant-fe/components/Home.tsx, jira-e2e-tests/integration/migration.ts, jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java, jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantProfileSpecificConfiguration.java, spi/src/main/java/com/atlassian/migration/datacenter/spi/MigrationReadyStatus.java, spi/src/main/java/com/atlassian/migration/datacenter/spi/MigrationReadyStatus.kt, spi/src/main/java/com/atlassian/migration/datacenter/spi/MigrationService.java
Kind of ugly, but the basic functionality is there.
=> CHET-378: Prerequisite checks

frontend/src/main/dc-migration-assistant-fe/api/fs.ts, frontend/src/main/dc-migration-assistant-fe/components/warning/CapturedFiles.tsx, frontend/src/main/dc-migration-assistant-fe/components/warning/WarningStage.tsx, frontend/src/main/resources/i18n/dc-migration-assistant.properties
* Implement component for showing list of files which were captured
* Render component in warning page
=> CHET-399: render captured files in offline warning page

core/pom.xml, core/src/main/java/com/atlassian/migration/datacenter/core/aws/auth/EncryptedCredentialsStorage.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArtifactS3UploadService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/restore/TargetDbCredentialsStorageService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/region/PluginSettingsRegionManager.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/ssm/SSMApi.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java, core/src/test/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArtifactS3UploadServiceTest.java, core/src/test/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationServiceTest.java, jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java, jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantOsgiImportConfiguration.java, jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/SpringOsgiConfigurationUtil.java, pom.xml
Use java util supplier, as used by `LazyReference` class from `io.atlassian.concurrent` libraries
=> Chet 408 fix supplier imports

frontend/src/main/dc-migration-assistant-fe/components/aws/AwsRoutes.tsx, frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickStartDeploy.tsx, frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/QuickstartRoutes.tsx, frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/asi/ASIConfiguration.tsx
* Hoist ASI prefix state into component above Quickstart form and ASI configuration page.
* Pass prefix down to quickstart form
* Override default value for `ExportPrefix` based on passed down ASI prefix.
=> Chet 427 use configured asi prefix

api/src/main/kotlin/com/atlassian/migration/datacenter/api/db/DatabaseMigrationEndpoint.kt
Tried to write a test but the `DatabaseMigrationService` and `S3FinalSyncService` weren't mocking 🤔
=> CHET-409: [api] don't start fs sync if db sync doesn't start

core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/QuickstartDeploymentService.java, spi/src/test/kotlin/com/atlassian/migration/datacenter/spi/infrastructure/ProvisioningConfigTest.kt
* Remove username from test
* Put resource bucket in variable
=> CHET-435: Changes missed before

core/pom.xml, core/src/main/java/com/atlassian/migration/datacenter/core/aws/SqsApi.kt, core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentService.java, core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentServiceTest.java, spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/infrastructure/MigrationInfrastructureDeploymentService.kt
Store queue resources and add a SQS API interface
=> Chet 443 store physical resource

core/src/main/java/com/atlassian/migration/datacenter/core/aws/SqsApi.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/EmptyQueueSqsApi.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/SqsApi.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/SqsApiImpl.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/exceptions/AwsQueueError.kt, core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/SqsApiIT.kt, core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/SqsApiImplTest.kt, core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/AtlassianInfrastructureServiceTest.kt
Create a SQS implementation to get queue count based on messages in flight and enqueued items
~TODO: Localstack integration test~
=> CHET-443: Add SQS API implementation and create tests

core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/AWSCleanupTaskFactory.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/MigrationBucketCleanupService.kt, core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/MigrationBucketCleanupServiceIT.kt, core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/MigrationBucketCleanupServiceTest.kt, jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
* Implement cleanup job for emptying the migration bucket
* Implement unit and integration test for the cleanup
=> CHET-453: empty migration bucket

core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/MigrationBucketCleanupService.kt, core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/MigrationBucketCleanupServiceIT.kt, core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/MigrationBucketCleanupServiceTest.kt
* Delete the bucket after emptying the bucket
* Extend unit and integration tests to ensure this works
=> CHET-454: delete migration bucket

core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentService.java, core/src/test/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentServiceTest.java
Ensure stack outputs are set after persisting values from CFn API
=> Chet 467 helper stack outputs

jira-e2e-tests/helpers/run-local, jira-plugin/src/main/resources/whitelist/analytics_whitelist.json
=> CHET-89: Fix analytics whitelist, and be more aggressive with container cleanup

.github/workflows/migration_template_uploader.yml
Skipping for branches other than `master`
=> CHET-298: Build and upload migration template for pushes to master

core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArtifactS3UploadService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseMigrationService.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/DefaultFilesystemUploader.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/FileUploadException.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/FilesystemUploader.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3Uploader.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/Uploader.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/copy/S3BulkCopy.java, core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/DefaultFilesystemUploaderFactory.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/FilesystemUploaderFactory.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/S3UploaderFactory.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/fs/UploaderFactory.kt, core/src/test/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationServiceIT.java, core/src/test/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationServiceTest.java, core/src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderIT.java, core/src/test/java/com/atlassian/migration/datacenter/core/fs/S3UploaderTest.java, core/src/test/java/com/atlassian/migration/datacenter/core/fs/copy/S3BulkCopyTest.java, jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
This depends on PR: https://github.com/atlassian-labs/dc-migration-assistant/pull/305
=> CHET-199: Make FilesystemUploader injectable

core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/DatabaseExtractor.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/PostgresExtractor.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/UnSupportedDatabaseExtractor.kt, core/src/test/kotlin/com/atlassian/migration/datacenter/core/db/PostgresExtractorIT.kt
Prior to creating `pg_dump` archive, check for and delete it if it exists.
=> CHET-546: Check for and delete pg_dump archive

frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/asi/ASIConfiguration.tsx, frontend/src/main/resources/i18n/dc-migration-assistant.properties
ASI Loading screen now looks like:
The `Next` button is put into a loading state to indicate things are happening. Once the ASI scan is complete the form updates accordingly...
=> CHET-465: Static info message for ASI loading

core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/BucketCleanupJobRunner.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/MigrationBucketCleanupService.kt, core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/BucketCleanupJobRunnerIT.kt, core/src/test/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/BucketCleanupJobRunnerTest.kt, jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java
This does not include the UI feedback.
=> CHET-492: Make final S3 cleanup async

frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx, frontend/src/main/dc-migration-assistant-fe/components/shared/MigrationTransferProgress.tsx, frontend/src/main/dc-migration-assistant-fe/components/shared/Progress.ts, frontend/src/main/resources/i18n/dc-migration-assistant.properties
Reverts atlassian-labs/dc-migration-assistant#356
=> Revert "CHET-560: Allow users to continue with migration despite failed file uploads"

api/src/main/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationEndpoint.kt, api/src/test/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationEndpointTest.kt, frontend/src/main/dc-migration-assistant-fe/components/fs/FileSystemTransfer.tsx, spi/src/main/kotlin/com/atlassian/migration/datacenter/spi/MigrationStage.kt, spi/src/test/kotlin/com/atlassian/migration/datacenter/spi/MigrationStageTest.kt
=> CHET-558: retry even when abort fails

frontend/src/main/dc-migration-assistant-fe/components/aws/auth/AuthenticateAWS.tsx
I just got annoyed with the region dropdown and was waiting for a migration.
@bpar476 my javascript testing fu is not great so I skipped the test for it now as we have other priorities but I would like to circle back on it and create a test (mostly to start writing some FE tests:)
=> CHET-500: Filter region select dropdown

api/pom.xml, api/src/main/kotlin/com/atlassian/migration/datacenter/api/FinalSyncEndpoint.kt, api/src/main/kotlin/com/atlassian/migration/datacenter/api/MigrationEndpoint.kt, api/src/main/kotlin/com/atlassian/migration/datacenter/api/application/ApplicationPropertiesEndpoint.kt, api/src/main/kotlin/com/atlassian/migration/datacenter/api/aws/AWSAvailabilityZoneEndpoint.kt, api/src/main/kotlin/com/atlassian/migration/datacenter/api/aws/AWSConfigureEndpoint.kt, api/src/main/kotlin/com/atlassian/migration/datacenter/api/aws/AWSGlobalInfrastructureEndpoint.kt, api/src/main/kotlin/com/atlassian/migration/datacenter/api/aws/AWSResourceCleanupEndpoint.kt, api/src/main/kotlin/com/atlassian/migration/datacenter/api/aws/CloudFormationEndpoint.kt, api/src/main/kotlin/com/atlassian/migration/datacenter/api/aws/TestAWSCredentialsEndpoint.kt, api/src/main/kotlin/com/atlassian/migration/datacenter/api/develop/DevelopEndpoint.kt, api/src/main/kotlin/com/atlassian/migration/datacenter/api/fs/FileSystemMigrationEndpoint.kt, api/src/test/kotlin/com/atlassian/migration/datacenter/api/MigrationEndpointTest.kt, api/src/test/kotlin/com/atlassian/migration/datacenter/api/application/ApplicationPropertiesEndpointTest.kt, core/src/main/java/com/atlassian/migration/datacenter/TemplateServlet.java, core/src/test/java/com/atlassian/migration/datacenter/TemplateServletTest.java, frontend/src/main/dc-migration-assistant-fe/utils/api.ts, jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantBeanConfiguration.java, jira-plugin/src/main/java/com/atlassian/migration/datacenter/configuration/MigrationAssistantOsgiImportConfiguration.java
Add WebSudo requirements for REST resources and for the servlet.
=> CHET-572: Add PermisionInterceptor to REST endpoints

core/src/main/java/com/atlassian/migration/datacenter/core/aws/AWSMigrationService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/CfnApi.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/DatabaseArchivalService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/restore/SsmPsqlDatabaseRestoreService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/db/restore/TargetDbCredentialsStorageService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/AWSMigrationHelperDeploymentService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/infrastructure/CloudformationDeploymentService.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/ssm/SSMApi.java, core/src/main/java/com/atlassian/migration/datacenter/core/aws/ssm/SuccessfulSSMCommandConsumer.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/DefaultFilesystemUploader.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/S3FilesystemMigrationService.java, core/src/main/java/com/atlassian/migration/datacenter/core/fs/copy/S3BulkCopy.java, core/src/main/java/com/atlassian/migration/datacenter/core/util/LogUtils.java, core/src/main/kotlin/com/atlassian/migration/datacenter/core/aws/infrastructure/cleanup/AWSMigrationStackCleanupService.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/PostgresExtractor.kt, core/src/test/java/com/atlassian/migration/datacenter/core/util/LogUtilsTest.java
=> CHET-564: Additional logging

.github/workflows/mvn_test.yml, api/pom.xml, core/pom.xml, filesystem-processor/pom.xml, frontend/pom.xml, jira-e2e-tests/helpers/run-local, jira-e2e-tests/helpers/upload-plugin, jira-e2e-tests/jira/Dockerfile, jira-plugin/pom.xml, pom.xml, spi/pom.xml
Create 1.0.1 release.
Once this is merged, bump the release version & create a 1.0.2-SNAPSHOT release PR
=> CHET-14: Prepare 1.0.1 release

.github/CODEOWNERS
Next step - Rewrite history and erase all traces from git permanently!
=> no-issue: remove that traitorous deserter from the project owner list

frontend/src/main/dc-migration-assistant-fe/components/aws/quickstart/asi/ExistingASIConfiguration.tsx, jira-e2e-tests/README.md, jira-e2e-tests/cypress/.eslintignore, jira-e2e-tests/cypress/.eslintrc.js, jira-e2e-tests/cypress/integration/full-migration.ts, jira-e2e-tests/cypress/integration/migration.ts, jira-e2e-tests/cypress/integration/smoketest.ts, jira-e2e-tests/cypress/package.json, jira-e2e-tests/cypress/support/common.ts, jira-e2e-tests/cypress/support/index.d.ts, jira-e2e-tests/cypress/support/index.js, jira-e2e-tests/cypress/support/migrationWorkflow.ts
First, pass for the full functional test. This will go through the first 3 steps - authenticate, select AWS, start deployment.
The next step is to wait for deployment but I will split it to another PR to not bloat this one.
=> CHET-616: Create test for full migration worklow up to provisioning step 

.github/workflows/mvn_test.yml, jira-e2e-tests/README.md, jira-e2e-tests/cypress/integration/full-migration.ts, jira-e2e-tests/cypress/integration/migration.ts, jira-e2e-tests/cypress/integration/smoketest.ts, jira-e2e-tests/cypress/support/index.js, jira-e2e-tests/docker-compose.yml, jira-e2e-tests/postgres/jira.sql.tmpl
Update the password in the DB and make it a stashed env variable for testing. The new password is stored in lastpass under "Jira E2E testing credentials".
=> CHET-617: Update the admin user password to something non-obvious.

frontend/src/main/dc-migration-assistant-fe/components/shared/CancelButton.tsx, frontend/src/main/dc-migration-assistant-fe/components/warning/WarningStage.tsx, jira-e2e-tests/cypress/integration/e2e_full_migration.ts, jira-e2e-tests/cypress/support/pages/BlockUsersPage.ts, jira-e2e-tests/cypress/support/pages/FileSystemMigration.ts, jira-e2e-tests/cypress/support/pages/ProvisioningPage.ts, jira-e2e-tests/cypress/support/pages/SelectAsiPage.ts, jira-e2e-tests/cypress/support/waiters.ts
* Starts FS migration
* Monitor FS migration
* Verify the *Block users* page
=> CHET-618: Monitor filesystem migration

.github/workflows/mvn_test.yml
=> no-issue: decommision deploy to dogfooding test

.github/workflows/mvn_test.yml, .github/workflows/snyk_security.yml
* Run the full test suite every day at midnight
* Run the Snyk security analysis on every push to default branch
=> Improve github actions triggers

.github/CODEOWNERS
Ben will be forever in the fabric of this repo in the commit history.
Adding Nasser to default reviewers
=> Updating default reviewers

core/pom.xml, core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/DatabaseClientTools.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/PostgresClientTooling.kt, core/src/main/kotlin/com/atlassian/migration/datacenter/core/db/PostgresExtractor.kt, jira-e2e-tests/.env
Vulnerability mitigation by removing the vulnerable dependencies 😛 
Reported vulnerability: https://snyk.io/vuln/SNYK-JAVA-IONETTY-564897
=> DCD-1179: Use PSQL query to deduce DB version

api/pom.xml, build-utils/pom.xml, core/pom.xml, filesystem-processor/pom.xml, frontend/pom.xml, jira-plugin/pom.xml, pom.xml, spi/pom.xml
=> Prepare release 1.1.6
